apiVersion: v1
kind: Secret
metadata:
  name: autoflow-auth
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.autoflow.adminUsername | default "admin" }}
  password: {{ .Values.autoflow.adminPassword | default "admin" }}