apiVersion: v1
kind: Service
metadata:
  name: autoflow-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: autoflow
  ports:
    - name: ui
      protocol: TCP
      port: {{ .Values.autoflow.uiPort | default "4000" }}
      targetPort: 4000
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
